# Generated by Django 5.1.7 on 2025-04-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetails',
            name='personal_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_details', to='kyc.userdetails'),
        ),
    ]
