# Generated by Django 5.1.7 on 2025-04-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_sessiondetails_personal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='document_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
